import time
import uuid
import datetime
import re
import logging
from typing import Optional, List, Dict, Any
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from .redactor import LogRedactor
from .guardrail import ONNXGuardrail
from .memory import StatefulMemoryManager
from .reasoning import SchemaEnforcer
from .simulation import StructuralSimulationEngine
from .action import AdaptivePlaybook, SovereignAuditLogger

logger = logging.getLogger(__name__)

app = FastAPI(title="AgentSOC Log Mitigation Gauntlet")

# Enable CORS for local dev & production frontend origins
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# WebSocket Connection Manager
class ConnectionManager:
    def __init__(self):
        self.active_connections: List[WebSocket] = []

    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        self.active_connections.append(websocket)
        logger.info(f"WebSocket client connected. Total active: {len(self.active_connections)}")

    def disconnect(self, websocket: WebSocket):
        if websocket in self.active_connections:
            self.active_connections.remove(websocket)
            logger.info(f"WebSocket client disconnected. Remaining: {len(self.active_connections)}")

    async def broadcast(self, message: Dict[str, Any]):
        for connection in list(self.active_connections):
            try:
                await connection.send_json(message)
            except Exception as e:
                logger.warning(f"Error broadcasting to WebSocket client ({e})")
                self.disconnect(connection)

ws_manager = ConnectionManager()

# Initialize core security components on startup
redactor = LogRedactor()
guardrail = ONNXGuardrail()
memory_manager = StatefulMemoryManager()
schema_enforcer = SchemaEnforcer()
simulation_engine = StructuralSimulationEngine()
playbook_generator = AdaptivePlaybook()
audit_logger = SovereignAuditLogger()

class LogPayload(BaseModel):
    log: str
    source_ip: Optional[str] = Field("10.0.0.1", description="Source IP telemetry token")
    target_ip: Optional[str] = Field("10.0.0.5", description="Target asset IP token")

@app.get("/")
async def root():
    return {
        "message": "AgentSOC Log Mitigation Gauntlet is running.",
        "websocket_endpoint": "/ws/telemetry",
        "ingest_endpoint": "/ingest"
    }

@app.websocket("/ws/telemetry")
async def websocket_telemetry_endpoint(websocket: WebSocket):
    await ws_manager.connect(websocket)
    try:
        while True:
            # Keep-alive receive loop
            data = await websocket.receive_text()
            await websocket.send_json({"status": "acknowledged", "echo": data})
    except WebSocketDisconnect:
        ws_manager.disconnect(websocket)
    except Exception as e:
        logger.warning(f"WebSocket error ({e})")
        ws_manager.disconnect(websocket)

@app.post("/ingest")
async def ingest_log(payload: LogPayload):
    start_time = time.perf_counter()
    incident_id = str(uuid.uuid4())
    timestamp_iso = datetime.datetime.now(datetime.timezone.utc).isoformat()
    security_flags = []
    
    # 1. Sub-millisecond character escaping (strip < and >)
    sanitized_text = payload.log.replace("<", "").replace(">", "")
    
    # 2. Offline Data Redaction (PII scanning and replacing)
    redacted_text = redactor.redact(sanitized_text)
    if redacted_text != sanitized_text:
        security_flags.append("PII_REDACTED")

    # Extract entity IDs (tokens) generated by the redactor
    tokens = re.findall(r"TOKEN:[a-f0-9]+", redacted_text)

    # 3. Stateful Graph Memory (Context Stitching Check)
    for token in tokens:
        if await memory_manager.check_context_stitching(token, redacted_text):
            security_flags.append("CONTEXT_STITCHING_DETECTED")
            latency = (time.perf_counter() - start_time) * 1000
            
            enriched_incident = {
                "incident_id": incident_id,
                "timestamp": timestamp_iso,
                "sanitized_payload": f"<log_data>{redacted_text}</log_data>",
                "structural_context": {
                    "source_ip": payload.source_ip,
                    "target_ip": payload.target_ip,
                    "criticality": "HIGH",
                    "zone": "DMZ-Production"
                },
                "security_flags": security_flags
            }
            
            hypothesis = await schema_enforcer.generate_hypothesis(enriched_incident, "blocked")
            sim_valid = simulation_engine.validate_attack_path(payload.source_ip, payload.target_ip)
            risk_score = simulation_engine.calculate_composite_score(0.95, hypothesis.confidence_score)
            workflow = playbook_generator.generate_workflow(hypothesis, risk_score)
            audit_ref = audit_logger.log_incident({
                "incident_id": incident_id,
                "status": "rejected",
                "reason": "Context Stitching Attack Detected",
                "enriched_incident": enriched_incident,
                "risk_score": risk_score
            })

            response_data = {
                "status": "rejected",
                "quarantined": True,
                "reason": "Context Stitching Attack Detected",
                "enriched_incident_object": enriched_incident,
                "incident_hypothesis": hypothesis.model_dump(),
                "simulation_valid": sim_valid,
                "composite_risk_score": risk_score,
                "playbook_workflow": workflow,
                "audit_log_ref": audit_ref,
                "pipeline_latency_ms": latency
            }

            # Broadcast incident to live WebSocket subscribers
            await ws_manager.broadcast(response_data)
            return response_data
            
    # Record the episode into memory for future checks
    for token in tokens:
        await memory_manager.ingest_episode(token, redacted_text)

    # 4. Real SLM Hardware Guardrail Check (evaluated on sanitized natural language text)
    guardrail_result = guardrail.scan(sanitized_text)
    if guardrail_result["status"] == "blocked":
        security_flags.append("SLM_PROMPT_INJECTION_DETECTED")
    else:
        security_flags.append("SLM_CHECK_PASSED")

    # Construct Enriched Incident Object
    final_payload = f"<log_data>{redacted_text}</log_data>"
    enriched_incident = {
        "incident_id": incident_id,
        "timestamp": timestamp_iso,
        "sanitized_payload": final_payload,
        "structural_context": {
            "source_ip": payload.source_ip,
            "target_ip": payload.target_ip,
            "criticality": "HIGH",
            "zone": "DMZ-Production"
        },
        "security_flags": security_flags
    }

    # 5. Multi-Agent Swarm Schema Enforcement Engine
    hypothesis = await schema_enforcer.generate_hypothesis(enriched_incident, guardrail_result["status"])
    
    # 6. Structural Simulation Engine & Risk Scoring
    sim_valid = simulation_engine.validate_attack_path(payload.source_ip, payload.target_ip)
    containment = 0.9 if guardrail_result["status"] == "blocked" else 0.3
    risk_score = simulation_engine.calculate_composite_score(containment, hypothesis.confidence_score)

    # 7. Adaptive Playbook Generation & Sovereign Audit Logging
    workflow = playbook_generator.generate_workflow(hypothesis, risk_score)
    audit_ref = audit_logger.log_incident({
        "incident_id": incident_id,
        "status": guardrail_result["status"],
        "enriched_incident": enriched_incident,
        "risk_score": risk_score,
        "hypothesis": hypothesis.model_dump()
    })

    latency = (time.perf_counter() - start_time) * 1000
    
    response_data = {
        "status": "success" if guardrail_result["status"] == "allowed" else "rejected",
        "guardrail": guardrail_result,
        "enriched_incident_object": enriched_incident,
        "incident_hypothesis": hypothesis.model_dump(),
        "simulation_valid": sim_valid,
        "composite_risk_score": risk_score,
        "playbook_workflow": workflow,
        "audit_log_ref": audit_ref,
        "processed_payload": final_payload,
        "pipeline_latency_ms": latency
    }

    # Broadcast incident to live WebSocket subscribers
    await ws_manager.broadcast(response_data)
    return response_data
